apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderation-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moderation
  template:
      metadata:
        labels:
          app: moderation
      spec:
        containers:
          - name: moderation
            image: sandratj/moderation
---
apiVersion: v1
kind: Service
metadata:
  name: moderation-srv
spec:
  selector:
    app: 
  ports:
    - name: moderation
      protocol: TCP
      port: 3003
      targetPort: 3003